package com.drools.conspiracies;
import javax.swing.JOptionPane

    declare Answer
        question : String
        answer : String
    end

    function Answer checkForAnswer7(int p, String question, String answer1, String answer2, String answer3, String answer4, String answer5, String answer6, String answer7){
                Answer answer = new Answer();
                answer.setQuestion(question);
                Object[] formatedOptions = {
                "<html><body><p style='width: 30px;'>"+answer1+"</p></body></html>",
                "<html><body><p style='width: 30px;'>"+answer2+"</p></body></html>",
                "<html><body><p style='width: 30px;'>"+answer3+"</p></body></html>",
                "<html><body><p style='width: 30px;'>"+answer4+"</p></body></html>",
                "<html><body><p style='width: 30px;'>"+answer5+"</p></body></html>",
                "<html><body><p style='width: 30px;'>"+answer6+"</p></body></html>",
                "<html><body><p style='width: 30px;'>"+answer7+"</p></body></html>"};
                Object[] options = {answer1, answer2, answer3, answer4, answer5, answer6, answer7};

                System.out.println(question);

                //first null - Parent Frame
                int n = JOptionPane.showOptionDialog(null,
                    question,
                    "Question"+p,
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    formatedOptions,
                    null);

                if (n == 0) {
                    System.out.println(options[0]);
                    answer.setAnswer(""+options[0]);

                }
                else if (n == 1) {
                    System.out.println(options[1]);
                    answer.setAnswer(""+options[1]);
                }
                else if (n == 2) {
                    System.out.println(options[2]);
                    answer.setAnswer(""+options[2]);
                }
                else if (n == 3) {
                    System.out.println(options[3]);
                    answer.setAnswer(""+options[3]);
                }
                else if (n == 4) {
                    System.out.println(options[4]);
                    answer.setAnswer(""+options[4]);
                }
                else if (n == 5) {
                    System.out.println(options[5]);
                    answer.setAnswer(""+options[5]);
                }
                else if (n == 6){
                    System.out.println(options[6]);
                    answer.setAnswer(""+options[6]);
                }
                else {
                    System.out.println("You choose to ignore the truth, huh?");
                    return null;
                    }

                return answer;
            }

    function Answer checkForAnswer6(int p, String question, String answer1, String answer2, String answer3, String answer4, String answer5, String answer6){
                Answer answer = new Answer();
                answer.setQuestion(question);
                Object[] formatedOptions = {
                "<html><body><p style='width: 50px;'>"+answer1+"</p></body></html>",
                "<html><body><p style='width: 50px;'>"+answer2+"</p></body></html>",
                "<html><body><p style='width: 50px;'>"+answer3+"</p></body></html>",
                "<html><body><p style='width: 50px;'>"+answer4+"</p></body></html>",
                "<html><body><p style='width: 50px;'>"+answer5+"</p></body></html>",
                "<html><body><p style='width: 50px;'>"+answer6+"</p></body></html>"};
                Object[] options = {answer1, answer2, answer3, answer4, answer5, answer6};

                System.out.println(question);

                //first null - Parent Frame
                int n = JOptionPane.showOptionDialog(null,
                    question,
                    "Question"+p,
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    formatedOptions,
                    null);

                if (n == 0) {
                    System.out.println(options[0]);
                    answer.setAnswer(""+options[0]);

                }
                else if (n == 1) {
                    System.out.println(options[1]);
                    answer.setAnswer(""+options[1]);
                }
                else if (n == 2) {
                    System.out.println(options[2]);
                    answer.setAnswer(""+options[2]);
                }
                else if (n == 3) {
                    System.out.println(options[3]);
                    answer.setAnswer(""+options[3]);
                }
                else if (n == 4) {
                    System.out.println(options[4]);
                    answer.setAnswer(""+options[4]);
                }
                else if (n == 5){
                    System.out.println(options[5]);
                    answer.setAnswer(""+options[5]);
                }
                else {
                    System.out.println("You choose to ignore the truth, huh?");
                    return null;
                    }

                return answer;
            }

    function Answer checkForAnswer5(int p, String question, String answer1, String answer2, String answer3, String answer4, String answer5){
                Answer answer = new Answer();
                answer.setQuestion(question);
                Object[] formatedOptions = {
                "<html><body><p style='width: 80px;'>"+answer1+"</p></body></html>",
                "<html><body><p style='width: 80px;'>"+answer2+"</p></body></html>",
                "<html><body><p style='width: 80px;'>"+answer3+"</p></body></html>",
                "<html><body><p style='width: 80px;'>"+answer4+"</p></body></html>",
                "<html><body><p style='width: 80px;'>"+answer5+"</p></body></html>"};
                Object[] options = {answer1, answer2, answer3, answer4, answer5};

                System.out.println(question);

                //first null - Parent Frame
                int n = JOptionPane.showOptionDialog(null,
                    question,
                    "Question"+p,
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    formatedOptions,
                    null);

                if (n == 0) {
                    System.out.println(options[0]);
                    answer.setAnswer(""+options[0]);

                }
                else if (n == 1) {
                    System.out.println(options[1]);
                    answer.setAnswer(""+options[1]);
                }
                else if (n == 2) {
                    System.out.println(options[2]);
                    answer.setAnswer(""+options[2]);
                }
                else if (n == 3) {
                    System.out.println(options[3]);
                    answer.setAnswer(""+options[3]);
                }
                else if (n == 4){
                    System.out.println(options[4]);
                    answer.setAnswer(""+options[4]);
                }
                else {
                    System.out.println("You choose to ignore the truth, huh?");
                    return null;
                    }

                return answer;
            }

    function Answer checkForAnswer4(int p, String question, String answer1, String answer2, String answer3, String answer4){
                Answer answer = new Answer();
                answer.setQuestion(question);
                Object[] formatedOptions = {
                "<html><body><p style='width: 100px;'>"+answer1+"</p></body></html>",
                "<html><body><p style='width: 100px;'>"+answer2+"</p></body></html>",
                "<html><body><p style='width: 100px;'>"+answer3+"</p></body></html>",
                "<html><body><p style='width: 100px;'>"+answer4+"</p></body></html>"};
                Object[] options = {answer1, answer2, answer3, answer4};

                System.out.println(question);

                //first null - Parent Frame
                int n = JOptionPane.showOptionDialog(null,
                    question,
                    "Question"+p,
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    formatedOptions,
                    null);

                if (n == 0) {
                    System.out.println(options[0]);
                    answer.setAnswer(""+options[0]);

                }
                else if (n == 1) {
                    System.out.println(options[1]);
                    answer.setAnswer(""+options[1]);
                }
                else if (n == 2) {
                    System.out.println(options[2]);
                    answer.setAnswer(""+options[2]);
                }
                else if (n == 3){
                    System.out.println(options[3]);
                    answer.setAnswer(""+options[3]);
                }
                else {
                    System.out.println("You choose to ignore the truth, huh?");
                    return null;
                    }

                return answer;
            }

    function Answer checkForAnswer3(int p, String question, String answer1, String answer2, String answer3){
                Answer answer = new Answer();
                answer.setQuestion(question);
                Object[] formatedOptions = {
                "<html><body><p style='width: 130px;'>"+answer1+"</p></body></html>",
                "<html><body><p style='width: 130px;'>"+answer2+"</p></body></html>",
                "<html><body><p style='width: 130px;'>"+answer3+"</p></body></html>"};
                Object[] options = {answer1, answer2, answer3};

                System.out.println(question);

                //first null - Parent Frame
                int n = JOptionPane.showOptionDialog(null,
                    question,
                    "Question"+p,
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    formatedOptions,
                    null);

                if (n == 0) {
                    System.out.println(options[0]);
                    answer.setAnswer(""+options[0]);

                }
                else if (n == 1) {
                    System.out.println(options[1]);
                    answer.setAnswer(""+options[1]);
                }
                else if (n == 2){
                    System.out.println(options[2]);
                    answer.setAnswer(""+options[2]);
                }
                else {
                    System.out.println("You choose to ignore the truth, huh?");
                    return null;
                    }

                return answer;
            }

    function Answer checkForAnswer2(int p, String question, String answer1, String answer2){
            Answer answer = new Answer();
            answer.setQuestion(question);
            Object[] formatedOptions = {
            "<html><body><p style='width: 150px;'>"+answer1+"</p></body></html>",
            "<html><body><p style='width: 150px;'>"+answer2+"</p></body></html>"};
            Object[] options = {answer1, answer2};

            System.out.println(question);

            //first null - Parent Frame
            int n = JOptionPane.showOptionDialog(null,
                question,
                "Question"+p,
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                formatedOptions,
                null);

            if (n == 0) {
                System.out.println(options[0]);
                answer.setAnswer(""+options[0]);

            }
            else if (n == 1) {
                System.out.println(options[1]);
                answer.setAnswer(""+options[1]);
            }
            else {
                System.out.println("You choose to ignore the truth, huh?");
                return null;
                }

            return answer;
        }

        function Answer youReWrong(int p, String question, String answer1){
            Answer answer = new Answer();
            answer.setQuestion(question);
            Object[] options = {answer1};

            System.out.println(question);

            //first null - Parent Frame
            int n = JOptionPane.showOptionDialog(null,
                question,
                "Question"+p,
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                null);

            if (n == 0) {
                System.out.println(options[0]);
                answer.setAnswer(""+options[0]);

            }
            else {
                System.out.println("You choose to ignore the truth, huh?");
                return null;
                }

            return answer;
        }

    rule "Ignition"
    when
        Starter()
        or
        Answer(question == "Well of course THEY would say that wouldn't THEY", answer == "Think again")
    then
        insert(checkForAnswer2(1, "Are the bastards out to get you?", "They say not", "Yes, they're up to something alright, I just know it."));
    end

    rule "Question1"
    when
        Answer(question == "Are the bastards out to get you?", answer == "Yes, they're up to something alright, I just know it.")
    then
        insert(checkForAnswer3(2, "Who do you suppose THEY are?", "Big Pharma", "Aliens", "THEM"));
    end

    rule "Question2"
    when
        answerQuestion : Answer(question == "Are the bastards out to get you?", answer == "They say not")
    then
        insert(youReWrong(2, "Well of course THEY would say that wouldn't THEY", "Think again"));
    end

    rule "Question3"
    when
        answerQuestion : Answer(question == "Who do you suppose THEY are?", answer == "Big Pharma")
    then
        insert(checkForAnswer2(3, "Big pharma are evil because...", "They use evil toxins", "Doctors tell you a crock of shit"));
    end

    rule "Question4"
    when
        answerQuestion : Answer(question == "Big pharma are evil because...", answer == "They use evil toxins")
    then
//            insert(checkForAnswer(3, "Big pharma are evil because...", "They use toxins", "Doctors tell you a crock of shit"));
    end