package com.drools.conspiracies;
import javax.swing.JOptionPane

    declare Answer
        question : String
        answer : String
    end

    //p - question number
    function Answer checkForAnswer(int p, String question, String answer1, String answer2){
        Answer answer = new Answer();
        answer.setQuestion(question);
        Object[] options = {answer1, answer2};

        int n = JOptionPane.showOptionDialog(null,
            question,
            "Question"+p,
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            options,
            null);

        if (n == 0) {
            System.out.println(options[0]);
            answer.setAnswer(""+options[0]);

        }
        else if (n == 1) {
            System.out.println(options[1]);
            answer.setAnswer(""+options[1]);
        }
        else {
            System.out.println("You choose to ignore the truth, huh?");
            return null;
            }

        return answer;
    }

    rule "Ignition"
    when
    then
        insert(checkForAnswer(1, "Are the bastards out to get you?", "They say not", "Yes, they're up to something alright, I just know it."));
    end

    rule "Question1"
    when
        answerQuestion : Answer(question == "Are the bastards out to get you?", answer == "Yes, they're up to something alright, I just know it.")
    then
        System.out.println("good boy");
    end

    rule "Question2"
    when
        answerQuestion : Answer(question == "Are the bastards out to get you?", answer == "They say not")
    then
        System.out.println("fuck");
    end

